name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
outputs:
  hello-text:
    description: 'Random number'
    value: ${{ steps.hello-text-generator.outputs.hello-text }}
runs:
  using: 'composite'
  steps:
    - id: hello-text-generator
      run: echo "hello-text=Hello,${{ inputs.who-to-greet }}" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo ${{ steps.hello-text-generator.outputs.hello-text }}
      shell: bash
    - run: sh ${{ github.action_path }}/goodbye.sh ${{ inputs.who-to-greet }}
      shell: bash
