name: 'Clone Test'

on:
  workflow_dispatch:
jobs:
  clone-repository:
    runs-on: ubuntu-latest

    steps:
      - run: cat $GITHUB_EVENT_PATH

      # GitHub Apps による認証トークンの発行
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # ゲーム開発リポジトリをクローン
      - name: Clone GameDev Repository
        run: |
          # --sparse --filter=blob:none オプションをつけてクローンを軽量化
          gh repo clone tigrig-study/youthsignal-volume-23 gamedev-repo -- --sparse --filter=blob:none
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

  checkout-repository:
    runs-on: ubuntu-latest

    steps:
      - run: cat $GITHUB_EVENT_PATH

      # GitHub Apps による認証トークンの発行
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # ゲーム開発リポジトリをチェックアウト
      - name: Checkout gamedev repository
        uses: actions/checkout@v3
        with:
          repository: tigrig-study/youthsignal-volume-23
          token: ${{ steps.generate_token.outputs.token }}
