name: Composite Action Test Example
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: echo 前処理:特になし

      - name: Exercise
        id: exercise
        uses: ./.github/actions/hello
        with:
          who-to-greet: world

      - name: Verify
        run: |
          test $EXPECTED = $ACTUAL
        env:
          ACTUAL: ${{ steps.exercise.outputs.hello-text }}
          EXPECTED: Hello,world

  teardown:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [test]
    if: always()
    steps:
      - uses: actions/checkout@v3
      - run: echo 後処理:特になし
